#!/bin/sh
#
#    debian-lts - list all the packages with ended or limited support
#    Copyright (C) 2015 Jan Wagner
#
#    Authors: Jan Wagner <waja@cyconet.org>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

if [ -x /usr/bin/check-support-status ]; then
	if [ -f /usr/share/custom-motd/scripts/custom-motd-functions ]
	then
		. /usr/share/custom-motd/scripts/custom-motd-functions
	fi
	TMPFILE=$(mktemp)
	trap "{ rm -rf ${TMPFILE}; }" EXIT
	check-support-status | grep "^  - " > ${TMPFILE}
	if [ $(wc -l ${TMPFILE} | awk {'print $1'}) -gt 0 ]; then
		echo "Installed packages with ended or limited (security) support:"
		echo ""
		cat ${TMPFILE}
		echo ""
	fi
else
	echo "To see (here) if all your installed packages are covered by LTS support, please"
	echo "install the package 'debian-security-support'!"
	echo ""
fi
